### ISSUE TITLE
MILESTONE 1 DOCUMENTATION

### ISSUE THREAD

**Issue by saxgetty** [Music-Discovery-Web-App/music-discovery#20]
[CSC 648 Reference](https://docs.google.com/document/d/1ZINkHEqznDIGz9nLv4FNorqXdAXqVfksH9wykQYGt1s/edit?usp=sharing)
[MDWA Document](https://docs.google.com/document/d/1yDc1E9zzQ2PSfx7vBZJbzRrID4Zq7MyAmSC3f7qTVlk/edit?usp=sharing)

- [x] Create Google document
- [x] Use our 648 document to reference
- [x] Create product summary @melissah717 
- [x] Create priority 1 feature list @saxgetty  
- [x] Create personae and use cases @mattrlee35 
- [x] Create main data items and entities @saxgetty @melissah717 @mattrlee35 
- [x] Create functional requirements @saxgetty @mattrlee35 
- [x] Create non-functional requirements @saxgetty @mattrlee35
